### ISSUE TITLE
Meeting Log 30-08-19

### ISSUE THREAD

**Issue by davisbk** [davisbk/thesis#10]
# Tasks Completed
- Created Jupyter notebook
- Discovered missing experiments and redid them
   - seed02 control condition
   - seed02 pop_up condition
- Started reading Hindré, et al (2012)
- Researched what box plots in paper ("How to Reduce a Genome?") represent

# Brian's To Do
- [x] Redo header images with labels
- [ ] Create counter-example images for header images (e.g. what is not in a functional CDS)
- [x] Fix graphs in Jupyter notebook
   - Is the correct column being graphed?
- [x] Plot different conditions
   - [x] metabolic error
   - [x] genome size
   - [x] number of coding sequences
   - [x] number of base pairs in CDS
   - [x] number of base pairs outside of CDS
- [x] Create Gantt chart
   - Tasks
   - How long to complete each task
- [x] Finish reading Hindré
- [ ] Keep working on thesis report
